import {
  Dumbbell,
  Footprints,
  Bike,
  Target,
  Book,
  Pen,
  Palette,
  Music,
  Gamepad2,
  Laptop,
  Microscope,
  Coffee,
  Salad,
  Apple,
  Droplet,
  Moon,
  Sun,
  Sprout,
  Flame,
  Star,
  Gem,
  Rocket,
  PartyPopper,
  Sparkles,
  Zap,
  Heart,
  Award,
  Trophy,
  Crown,
  Users,
  Smile,
  LucideIcon,
} from 'lucide-react-native';

export const ICON_MAP: Record<string, LucideIcon> = {
  dumbbell: Dumbbell,
  footprints: Footprints,
  bike: Bike,
  target: Target,
  book: Book,
  pen: Pen,
  palette: Palette,
  music: Music,
  gamepad: Gamepad2,
  laptop: Laptop,
  microscope: Microscope,
  coffee: Coffee,
  salad: Salad,
  apple: Apple,
  droplet: Droplet,
  moon: Moon,
  sun: Sun,
  sprout: Sprout,
  flame: Flame,
  star: Star,
  gem: Gem,
  rocket: Rocket,
  party: PartyPopper,
  sparkles: Sparkles,
  zap: Zap,
  heart: Heart,
  award: Award,
  trophy: Trophy,
  crown: Crown,
  users: Users,
  smile: Smile,
};

export function getIconComponent(iconName: string): LucideIcon {
  return ICON_MAP[iconName] || Target; // Target par défaut si l'icône n'existe pas
}
